name: Github Container Registry Cleaner
on:
  workflow_dispatch
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
  delete_old_images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete tagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          tags: pr*
          dry-run: true
          token: ${{ secrets.GITHUB_TOKEN }}
