name: Github Container Registry Cleaner

on:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: data-science-1
          cut-off: One hour ago UTC
          keep-at-least: 1
          filter-tags: latest, v*.*.*
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: data-science-0
          cut-off: One hour ago UTC
          skip-tags: latest, v*.*.*
          keep-at-least: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
